vich_uploader:
    db_driver: orm

    mappings:
        images:
           uri_prefix: '%app.path.images%'
           namer: Vich\UploaderBundle\Naming\UniqueidNamer
           upload_destination: '%kernel.project_dir%/public%app.path.images%'